const ItemsLevel1 = [
  {
    id: 1,
    contract_id: 1,
    code: "1",
    title: "SUB HEAD - I FEEDER PILLARS",
    description: "",
    added_dt: null,
    seq: 1,
    parent_id: null,
    ilevel: 0,
    extra_measurement_id: null,
    quantity: null,
    unit: "",
    rate: null,
    amount: null,
    formula_id: null,
    created_by: 1,
    updated_by: null,
    created_at: "2021-07-11T09:40:51.048Z",
    updated_at: "2021-07-12T11:39:51.205Z",
    version: 3,
  },
  {
    id: 19,
    contract_id: 1,
    code: "2",
    title: "SUB HEAD - II STREET LIGHTING",
    description: "",
    added_dt: null,
    seq: 24,
    parent_id: null,
    ilevel: 0,
    extra_measurement_id: null,
    quantity: null,
    unit: null,
    rate: null,
    amount: null,
    formula_id: null,
    created_by: 1,
    updated_by: 1,
    created_at: "2021-07-11T09:40:51.530Z",
    updated_at: "2021-07-11T09:40:51.530Z",
    version: 1,
  },
  {
    id: 26,
    contract_id: 1,
    code: "3",
    title: "SUB-HEAD-III - SPORTS LIGHTING",
    description: "",
    added_dt: null,
    seq: 32,
    parent_id: null,
    ilevel: 0,
    extra_measurement_id: null,
    quantity: null,
    unit: "",
    rate: null,
    amount: null,
    formula_id: null,
    created_by: 1,
    updated_by: null,
    created_at: "2021-07-11T09:40:51.719Z",
    updated_at: "2021-07-12T02:53:44.319Z",
    version: 17,
  },
  {
    id: 34,
    contract_id: 1,
    code: "4",
    title: "SUB HEAD IV - CABLE & PIPE LAYING",
    description: "",
    added_dt: null,
    seq: 41,
    parent_id: null,
    ilevel: 0,
    extra_measurement_id: null,
    quantity: null,
    unit: null,
    rate: null,
    amount: null,
    formula_id: null,
    created_by: 1,
    updated_by: 1,
    created_at: "2021-07-11T09:40:51.926Z",
    updated_at: "2021-07-11T09:40:51.926Z",
    version: 1,
  },
  {
    id: 78,
    contract_id: 1,
    code: "5",
    title: "SUB HEAD V - EARTHING",
    description: "",
    added_dt: null,
    seq: 86,
    parent_id: null,
    ilevel: 0,
    extra_measurement_id: null,
    quantity: null,
    unit: null,
    rate: null,
    amount: null,
    formula_id: null,
    created_by: 1,
    updated_by: 1,
    created_at: "2021-07-11T09:40:53.028Z",
    updated_at: "2021-07-11T09:40:53.028Z",
    version: 1,
  },
];


export default ItemsLevel1;