const tableData1 = [
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
  {
    id: 1,
    first_name: "Manender",
    last_name: "Kumar",
    email: "manender.kumar@mamsys.com",
    username: "manender",
    active: true,
    last_login: new Date(),
  },
];

export default tableData1;
